import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar/NavBar";
// import { TokenProvider } from "@/components/TokenContext/token-context";
import QueryClientWrapper from "@/components/AdminUserDashboard/QueryClientWrapper";
import { AuthProvider } from "@/services/authContext/authContext";


const roboto = Roboto({
  weight: ["300", "400", "700"],
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Splity",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="flex justify-center">
      <body className={`${roboto.variable} antialiased bg-gradient-to-b from-blue-500 to-indigo-600 text-gray-700`}>
     <QueryClientWrapper>
      <AuthProvider>
        {/* <TokenProvider> */}
          <NavBar />
          <div className="main-container min-h-screen w-full max-w-7xl mx-auto px-4">
            {children}
          </div>
        {/* </TokenProvider> */}
        </AuthProvider>
        </QueryClientWrapper>
      </body>
    </html>
  );
}
