import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar/NavBar";
//import dynamic from 'next/dynamic';
import { ChatBotWrapper } from "@/components/ChatBot/ChatBotWrapper";

// import { TokenProvider } from "@/components/TokenContext/token-context";
import QueryClientWrapper from "@/components/Boards/AdminUserDashboard/QueryClientWrapper";
import { AuthProvider } from "@/context/AuthContext";
import { GroupProvider } from "@/context/GroupContext";
import { ExpensesProvider } from "@/context/ExpensesContext";
import { MembershipProvider } from "@/context/MembershipContext";
import { BalanceProvider } from "@/context/BalanceContext";

const roboto = Roboto({
  weight: ["300", "400", "700"],
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Splity",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased bg-[#0d101b]`}>
        <QueryClientWrapper>
          <AuthProvider>
            <MembershipProvider>
              <GroupProvider>
                <ExpensesProvider>
                  <BalanceProvider>
                    <NavBar />
                    <div className="main-container">
                      {children}
                    </div>
                    <ChatBotWrapper />
                  </BalanceProvider>  
                </ExpensesProvider>
              </GroupProvider>
            </MembershipProvider>
          </AuthProvider>
        </QueryClientWrapper>
      </body>
    </html>
  );
}