import type { Metadata } from "next";
import { Inria_Sans } from "next/font/google";
import "./globals.css";

const inriaSans = Inria_Sans({
  weight: ["300"],
  variable: "--font-inria-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Splity",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en" className="h-[912px] flex justify-center bg-[url('/bg-retro.jpg')] bg-repeat">
      <body className={`${inriaSans.variable} antialiased w-[417px] shadow-2xl`}>
        {children}
      </body>
    </html>
  );
}
